config/routes.rb
Todoapp::Application.routes.draw do
  get "session/new"

  get "session/create"

  get "session/destroy"

  resources :tasks

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :assignee, :description, :due_date, :owner
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :confirmed_at, :email, :full_name, :pass, :password_confirmation, :role, :username, :word
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todoapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.haml
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :due_date
    = f.datetime_select :due_date
  .field
    = f.label :owner
    = f.text_field :owner
  .field
    = f.label :assignee
    = f.text_field :assignee
  .actions
    = f.submit 'Save'

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Show', @task
\|
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%h1 Listing tasks

%table
  %tr
    %th Description
    %th Due date
    %th Owner
    %th Assignee
    %th
    %th
    %th

  - @tasks.each do |task|
    %tr
      %td= task.description
      %td= task.due_date
      %td= task.owner
      %td= task.assignee
      %td= link_to 'Show', task
      %td= link_to 'Edit', edit_task_path(task)
      %td= link_to 'Destroy', task, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Task', new_task_path

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', tasks_path

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @task.description
%p
  %b Due date:
  = @task.due_date
%p
  %b Owner:
  = @task.owner
%p
  %b Assignee:
  = @task.assignee

= link_to 'Edit', edit_task_path(@task)
\|
= link_to 'Back', tasks_path